### ISSUE TITLE
проблема при инсталле

### ISSUE THREAD

**Issue by knopka2** [klypkan/yii-cms#1]
висит Installation Checker , долго и не выпадает

**Comment by klypkan** [comment]
Посмотрите логи веб сервера, видимо происходит какое-то исключение (Exception) из-за которого php код не может быть выполнен.

**Comment by knopka2** [comment]
попробовал на ospanel  включил E_ALL  ошибок 0
висит и крутится

**Comment by knopka2** [comment]
PDOException: invalid data source name in C:\OSPanel\domains\cms2.loc\vendor\yiisoft\yii2\db\Connection.php:687
включил 7 php, появились ошибки

**Comment by knopka2** [comment]
14-Feb-2019 20:48:09 Europe/Moscow] PHP Warning:  Cannot modify header information - headers already sent by (output started at C:\OSPanel\domains\cms2.loc\install.php:1) in C:\OSPanel\domains\cms2.loc\install.php on line 69
[14-Feb-2019 20:49:59 Europe/Moscow] PHP Warning:  Cannot modify header information - headers already sent by (output started at C:\OSPanel\domains\cms2.loc\site1\web\install.php:1) in C:\OSPanel\domains\cms2.loc\site1\web\install.php on line 69

**Comment by klypkan** [comment]
Я тестировал только на Apache. На ospanel не тестировал, возможно есть какие-то особенности. Протестирую на выходных, потом отпишусь.

**Comment by knopka2** [comment]
https://ospanel.io/
Open Server Panel — это портативная серверная платформа и программная среда, созданная специально для веб-разработчиков с учётом их рекомендаций и пожеланий.

**Comment by klypkan** [comment]
PDOException не связан с установкой, это исключение возникает при попытке запуска приложения (index.php) до завершения процесса установки. Поведение корректное т.к. строка содинения еще не установлена.
"PHP Warning: Cannot modify header information" эта ошибка возникает из-за попытки вывода какой-то ошибки. Попробуйте в панели разработчика браузера (F12) посмотреть ответ веб сервера (закладка Network).

**Comment by knopka2** [comment]
http://alphansk.ru/install.php

**Comment by klypkan** [comment]
Да действительно была такая проблема, проявлялась только при использовании Open Server Panel. 
Проблему исправил. Замените файл install.php
Спасибо за обратную связь!
