### ISSUE TITLE
не хватает установки картинки записи

### ISSUE THREAD

**Issue by knopka2** [klypkan/yii-cms#2]

**Comment by klypkan** [comment]
Сейчас пока занят, возможно ближе к концу месяца добавлю.

**Comment by klypkan** [comment]
Добавил картинку для Post.
Для того чтобы обновить уже установленную yii-cms, скачайте новую версию и замените в ней
файлы common/config/main.php и site1/config/main.php на те что есть в установленной версии.
Спасибо за обратную связь!
